# Generated by Django 4.0.6 on 2022-07-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequestsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('MERGED', 'Merged')], default='OPEN', max_length=6)),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.CharField(max_length=255)),
            ],
        ),
    ]
