# Generated by Django 4.0.6 on 2022-07-10 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_rename_pullrequestsmodels_pullrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='merged_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
