# Generated by Django 4.0.6 on 2022-07-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_pullrequest_closed_date_pullrequest_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
