# Generated by Django 4.0.6 on 2022-07-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0004_alter_pullrequest_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='closed_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='merged_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
